on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest 
    name: A job to say hello 
    steps: 
      - uses: actions/checkout@v3
      - id: foo
        uses: amirmarmul/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mr Marmul'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash 

